name:                hcl
version:             0.1.0.0
github:              "Sehktel/hcl"
license:             MIT
author:              "Sehktel"
maintainer:          "sehktel@example.com"
copyright:           "2024 Sehktel"

extra-source-files:
- README.md
- CHANGELOG.md

# Краткое описание проекта
synopsis:            Haskell C51 Compiler - компилятор C для микроконтроллеров 8051
category:            Compiler

# Подробное описание
description:         |
  HCL (Haskell C51 Compiler) - это компилятор языка C, специально разработанный
  для микроконтроллеров семейства 8051 (AT89S4051). Компилятор написан на Haskell
  и обеспечивает эффективную генерацию кода для ограниченных ресурсов микроконтроллера.
  
  Основные возможности:
  * Полная поддержка синтаксиса C для 8051
  * Специальные расширения для работы с регистрами SFR и битами
  * Оптимизации для минимизации использования памяти
  * Поддержка обработчиков прерываний
  * Модульная архитектура с четким разделением фаз компиляции

dependencies:
- base >= 4.7 && < 5
- text >= 1.2 && < 3
- bytestring >= 0.10 && < 1
- containers >= 0.6 && < 1
- mtl >= 2.2 && < 3
- transformers >= 0.5 && < 1
- megaparsec >= 9.0 && < 10
- parser-combinators >= 1.3 && < 2
- prettyprinter >= 1.7 && < 2
- optparse-applicative >= 0.16 && < 1
- filepath >= 1.4 && < 2
- directory >= 1.3 && < 2
- process >= 1.6 && < 2
- time >= 1.9 && < 2
- aeson >= 2.0 && < 3
- yaml >= 0.11 && < 1
- vector >= 0.12 && < 1
- regex-tdfa >= 1.3 && < 2

# Настройки по умолчанию для всех компонентов
default-extensions:
- OverloadedStrings
- LambdaCase
- MultiWayIf
- RecordWildCards
- NamedFieldPuns
- TupleSections
- DerivingStrategies
- DeriveGeneric
- DeriveAnyClass
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- FlexibleContexts
- FlexibleInstances
- TypeApplications
- ScopedTypeVariables
- ConstraintKinds
- RankNTypes

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - HCL.Lexer
  - HCL.Parser
  - HCL.AST
  - HCL.IR.HIR
  - HCL.IR.MIR
  - HCL.Preprocessor
  - HCL.Types
  - HCL.Error
  - HCL.Config
  - HCL.Logger
  - HCL.Optimizer
  - HCL.CodeGen
  - HCL.Utils

executables:
  hcl-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcl

tests:
  hcl-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcl
    - hspec >= 2.7 && < 3
    - QuickCheck >= 2.14 && < 3
    - hspec-discover >= 2.7 && < 3

benchmarks:
  hcl-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hcl
    - criterion >= 1.5 && < 2 